### ISSUE TITLE
pyarrow should be an output of arrow-cpp

### ISSUE THREAD

**Issue by pearu** [conda-forge/pyarrow-feedstock#107]
Issue:

https://github.com/conda-forge/pyarrow-feedstock/pull/101#issuecomment-629475808

Discussion:

Ideally, arrow-cpp and pyarrow packages should be built in sync whenever a new arrow update will be available. To ensure that, pyarrow ought to be added to arrow-cpp as the third output.

**Comment by h-vetinari** [comment]
I agree that this would be cleaner. It's all built from the same source anyway.

**Comment by jakirkham** [comment]
Agree this would make sense.

**Comment by jakirkham** [comment]
cc @conda-forge/arrow-cpp

**Comment by xhochy** [comment]
Happy to have that all in a single recipe as long as someone volunteers to build it ;)
