### ISSUE TITLE
`pyarrow` 16.1.0 reports incorrect version

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/pyarrow-feedstock#129]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

According to `mamba` I have `pyarrow=16.1.0` installed.

According to `pyarrow` itself, it is 14.0.2.

```python
In [1]: !micromamba list -n dev310 pyarrow
List of packages in environment: "/opt/python/envs/dev310"

  Name            Version  Build                Channel    
─────────────────────────────────────────────────────────────
  pyarrow         16.1.0   py310hb7f781d_4      conda-forge
  pyarrow-core    16.1.0   py310h46b3431_4_cpu  conda-forge
  pyarrow-hotfix  0.6      pyhd8ed1ab_0         conda-forge

In [2]: import pyarrow as pa

In [3]: pa.__version__
Out[3]: '14.0.2'

In [4]: from importlib.metadata import version

In [5]: version('pyarrow')
Out[5]: '14.0.2'
```

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by amoeba** [comment]
Hi @dhirschfeld, I wonder if something is mixed up in your environment. What does `print(pa)` return after you've run your above commands?

**Comment by dhirschfeld** [comment]
Hmm, yeah - it works in a new environment so it seems something is stuffed up in my existing environment :thinking:

Sorry for the noise!

**Comment by amoeba** [comment]
No worries. Feel free to join the [Arrow Zulip](https://ursalabs.zulipchat.com) and start a thread in `help/c++` if you can't get unstuck.

**Comment by dhirschfeld** [comment]
I nuked the package in my cache and site-packages, did a `--force-reinstall` and I can't import `pyarrow`.

If I copy the `.conda` package and extract it, it seems empty?!?
```bash
❯ cp /opt/python/pkgs/pyarrow-16.1.0-py310hb7f781d_4.conda ./

❯ cph x pyarrow-16.1.0-py310hb7f781d_4.conda 

❯ eza -T pyarrow-16.1.0-py310hb7f781d_4
pyarrow-16.1.0-py310hb7f781d_4
└── info
   ├── about.json
   ├── files
   ├── git
   ├── hash_input.json
   ├── index.json
   ├── licenses
   │  └── LICENSE.txt
   ├── paths.json
   ├── recipe
   │  ├── conda_build_config.yaml
   │  ├── meta.yaml
   │  └── parent
   │     ├── build-pyarrow.bat
   │     ├── build-pyarrow.sh
   │     ├── conda_build_config.yaml
   │     ├── meta.yaml
   │     ├── patches
   │     │  ├── 0001-fixture-teardown-should-not-fail-test.patch
   │     │  ├── 0002-MINOR-Python-try-harder-to-set-up-s3_server-fixture-.patch
   │     │  ├── 0003-MINOR-Python-Increase-timeout-in-TestThreadedCSVTabl.patch
   │     │  └── 0004-GH-41924-Python-Fix-tests-when-using-NumPy-2.0-on-Wi.patch
   │     ├── recipe-scripts-license.txt
   │     └── test_read_parquet.py
   └── test
      ├── run_test.py
      ├── run_test.sh
      └── test_read_parquet.py

```

**Comment by dhirschfeld** [comment]
Ok, it seems `pyarrow` is a metapackage so that makes sense. It seems my problem is trying to convince `mamba` to install any of the dependencies specified in the metapackage :/

**Comment by dhirschfeld** [comment]
No idea what was going on. I had to install with `conda` then uninstall and reinstall with `mamba` to get it working 😅

**Comment by dhirschfeld** [comment]
Maybe time I nuked my environment and started from scratch!

**Comment by amoeba** [comment]
If you're able to reproduce this in a clean environment (container, vm, or otherwise), let us know.
