### ISSUE TITLE
ImportError: No module named _config (when importing pyarrow.parquet)

### ISSUE THREAD

**Issue by derringdo** [conda-forge/pyarrow-feedstock#26]
I have the same issue as in:

https://github.com/conda-forge/pyarrow-feedstock/issues/20#issuecomment-289266763

>>> import pyarrow.parquet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/__init__.py", line 28, in <module>
    import pyarrow._config
ImportError: No module named _config

I used instructions at https://arrow.apache.org/docs/python/install.html to build arrow/cpp, parquet-cpp, and then pyarrow, with the following deviations (I view them as possibly bugs in the instructions):

1. arrow/cpp build:
  export ARROW_HOME=$HOME/local 
 I had to specify -DARROW_PYTHON=on and -DPARQUET_ARROW=ON to the cmake command (besides the -DCMAKE_INSTALL_PREFIX=$ARROW_HOME)

2. parquet-cpp build:

   export ARROW_HOME=$HOME/local

   cmake -DARROW_HOME=$HOME/local -DPARQUET_ARROW_LINKAGE=static -DPARQUET_ARROW=ON .
   make

   sudo make install ----> this installs parquet libs in the std systems location (/usr/local/lib) so that the pyarrow build (see below) can find the parquet libs

3. pyarrow build:

    export ARROW_HOME=$HOME/local (not a deviation; just repeating here)

    export LD_LIBRARY_PATH=$HOME/local/lib:$HOME/parquet4/parquet-cpp/build/latest

    sudo python setup.py build_ext --with-parquet --with-jemalloc --build-type=release install

    sudo python setup.py install

    (sudo is needed to install in /usr/local/lib/python2.7/dist-packages )

These are the steps and modifications to the instructions needed for me to build the pyarrow.parquet package. However, when I now try to import the package I get the error specified above.

Maybe I did something wrong in my steps which I kind of put together by searching for these issues...but really can't tell what. It took me almost a whole day to get to the point where I can build pyarrow and parquet, and now I can't use what I built.

Any comments, help appreciated! Thanks in advance.

**Comment by derringdo** [comment]
I forgot to mention this is on Ubuntu.

**Comment by wesm** [comment]
This is for conda packages. Can you try `conda install pyarrow -c conda-forge`? That should work. Thanks
