### ISSUE TITLE
No Builds for 0.6,win,py35

### ISSUE THREAD

**Issue by xhochy** [conda-forge/pyarrow-feedstock#37]
The current 0.6.0 package has not been built for the combination of Windows and Python 3.5, thus packages depending on it will fail for this combination.

**Comment by wesm** [comment]
I'm pushing an updated build for 0.6.0, but we'll want to get everyone onto 0.7.0 ASAP

**Comment by xhochy** [comment]
This has already been resolved some time ago, closing.
