### ISSUE TITLE
New release doesn't include ORC support

### ISSUE THREAD

**Issue by jcrist** [conda-forge/pyarrow-feedstock#46]
The `build.sh` doesn't include `--with-orc` in the call to `setup.py`. cc @cpcloud, @wesm.

**Comment by cpcloud** [comment]
I'll add it.

**Comment by jcrist** [comment]
I just restarted https://github.com/conda-forge/pyarrow-feedstock/pull/44, which should pass since the C++ build does include ORC support.

**Comment by cpcloud** [comment]
Oh, whoops. Ok. I'll close mine.

**Comment by jcrist** [comment]
Fixed by #44.
