### ISSUE TITLE
Use of parquet-cpp 1.5.0.pre

### ISSUE THREAD

**Issue by msarahan** [conda-forge/pyarrow-feedstock#56]
I'm attempting to update Anaconda's arrow-cpp and pyarrow recipes.  I'm having some trouble with how things have been changed.  Specifically:

* parquet-cpp 1.5.0 (tagged) relies on an arrow-cpp class that is not defined in arrow-cpp 0.10.0 (AllocateEmptyBitmap).
* parquet-cpp 1.4.0 is broken by arrow-cpp 0.10.0.

It appears that it is only possible to build pyarrow with an untagged parquet-cpp version.  We don't really like to build against arbitrary commits, as it seems you are doing with parquet-cpp right now (labelling the version .pre, which does not correspond to a tag, does not confer what software you're actually running).

The plan appears to be to fold parquet-cpp back into arrow-cpp (https://github.com/apache/parquet-cpp/compare/apache-parquet-cpp-1.5.0...master#diff-af3b638bc2a3e6c650974192a53c7291R21) - can anyone comment on a timescale for that?  Can there be an arrow-cpp 0.10.1 release that works with the tagged parquet-cpp 1.5.0 in the meantime?

**Comment by wesm** [comment]
We're anywhere from 1-2 weeks from Arrow 0.11 which will contain the Parquet libraries bundled, to avoid the mess that you've articulated.

**Comment by msarahan** [comment]
OK, thanks!  I guess we'll wait for that.  We'll keep an eye out for the tag.
