### ISSUE TITLE
pyarrow==0.15.1 requires Python 3.7?

### ISSUE THREAD

**Issue by Tagar** [conda-forge/pyarrow-feedstock#92]
We're still on Python 3.6

```
$ conda install conda-forge::pyarrow==0.15.1
```

produces following conflicts:

```
Package openssl conflicts for:
python==3.6.6 -> openssl[version='>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a']
conda-forge::pyarrow==0.15.1 -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a']
Package python-dateutil conflicts for:
conda-forge::pyarrow==0.15.1 -> pandas -> python-dateutil[version='>=2.5.*|>=2.6.1']
Package python conflicts for:
python==3.6.6

```

Notice `conda-forge::pyarrow==0.15.1 -> python[version='>=3.7,<3.8.0a0']` part 

pyarrow==0.15.1 requires Python 3.7?

**Comment by xhochy** [comment]
`pyarrow` should be available for Python 3.6. Can you retry again (we have uploaded a new build)? 

If it is still not working: Which OS are you using?

**Comment by Tagar** [comment]
thank you @xhochy 

We settled on 0.13 for now.. I can give this another try though 

Can you please point me to commit that should have fixes things for Python 3.6? just for understanding

**Comment by xhochy** [comment]
There was no change regarding 3.6, we simply have uploaded a new built. My main guess is that one of the builds has failed previous for 0.15.1 as we have a build per (OS, Python version) combination. If one is missing than you get the above error. 

A different suspicion I have is that you mix package from defaults and conda-forge? This could also lead to the above error. Please don't do this as this will lead to unexpected segfaults. defaults and conda-forge are independent and sometime incompatible distributions.

**Comment by Tagar** [comment]
@xhochy understood - thank you for the details

We recently stopped mixing defaults and conda-forge .. learned that hard way some time back as we were getting some run-time linking errors in one of boost libraries. (that unrelated to this issue, but now it reinforces that we should not mix those conda channels )
